export const listaIconejz = [
  { nombre: 'Flecha hacia arriba', codigo: 'jz-a-u' },
  { nombre: 'Flecha hacia la derecha', codigo: 'jz-a-rg' },
  { nombre: 'Flecha hacia abajo', codigo: 'jz-a-d' },
  { nombre: 'Flecha hacia la izquierda', codigo: 'jz-a-lf' },
  { nombre: 'Youtube', codigo: 'jz-yt' },
  { nombre: 'Instagram', codigo: 'jz-ig' },
  { nombre: 'Menu Hamburguesa', codigo: 'jz-m' },
  { nombre: 'Lupa', codigo: 'jz-mg' },
  { nombre: 'Check', codigo: 'jz-ck' },
  { nombre: 'X', codigo: 'jz-x' },
  { nombre: 'Tres puntos verticales', codigo: 'jz-tvp' },
  { nombre: 'Tres puntos horizontales', codigo: 'jz-thp' },
  { nombre: 'Candado', codigo: 'jz-plk' },
  { nombre: 'Candado abierto', codigo: 'jz-oplk' },
  { nombre: 'Carrito de compras', codigo: 'jz-sc' },
  { nombre: 'Ubicación', codigo: 'jz-lc', transparencia: false },
  { nombre: 'Usuario', codigo: 'jz-us' },
  { nombre: 'Usuario nuevo', codigo: 'jz-usn' },
  { nombre: 'Ajustes', codigo: 'jz-stt', transparencia: false },
  { nombre: 'Compartir', codigo: 'jz-shr' },
  { nombre: 'Casa', codigo: 'jz-hm' },
  { nombre: 'Estrella', codigo: 'jz-str' },
  { nombre: 'Peligro', codigo: 'jz-wng', transparencia: false },
  { nombre: 'Mensaje', codigo: 'jz-sms', transparencia: false },
  { nombre: 'Camara', codigo: 'jz-cam', transparencia: false },
  { nombre: 'Más', codigo: 'jz-plus' },
  { nombre: 'Menos', codigo: 'jz-minus' },
  { nombre: 'Descarga Completada', codigo: 'jz-dwl-c' },
  { nombre: 'Pausa', codigo: 'jz-pause' },
  { nombre: 'Play', codigo: 'jz-play' },
  { nombre: 'Información', codigo: 'jz-info' },
  { nombre: 'Doble Check', codigo: 'jz-dbl-ck' },
  { nombre: 'Copiar', codigo: 'jz-copy' },
  { nombre: 'Portapapeles', codigo: 'jz-clipboard' },
  { nombre: 'Anterior', codigo: 'jz-prev' },
  { nombre: 'Siguiente', codigo: 'jz-next' },
  { nombre: 'Descarga', codigo: 'jz-dwl' },
  { nombre: 'Lápiz', codigo: 'jz-pcl' },
  { nombre: 'Tachuela', codigo: 'jz-tack' },
  { nombre: 'Papelera', codigo: 'jz-ppb' },
  { nombre: 'Corazon', codigo: 'jz-heart' },
  { nombre: 'Shell', codigo: 'jz-sh' },
  { nombre: 'Github', codigo: 'jz-github', transparencia: false },
  { nombre: 'Git', codigo: 'jz-git', transparencia: false },
  { nombre: 'HTML', codigo: 'jz-html', transparencia: false },
  { nombre: 'CSS', codigo: 'jz-css', transparencia: false },
  { nombre: 'Javascript', codigo: 'jz-js', transparencia: false },
  { nombre: 'Markdown', codigo: 'jz-md', transparencia: false },
  { nombre: 'Texto', codigo: 'jz-txt' },
  { nombre: 'Correo', codigo: 'jz-email', transparencia: false },
];